[package]
name = "discord-fs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
fuser = "0.12.0"
libc = "0.2.139"
clap = { version = "3.0", features = ["cargo"] }
